{
 "title": "R710",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "cpu-user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" }
     ]
    },
    {
     "alias": "cpu-system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" }
     ]
    },
    {
     "alias": "cpu-nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" }
     ]
    }
   ]
  },
  {
   "title": "Mem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "mem-free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "mem-active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "load5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" }
     ]
    }
   ]
  },
  {
   "title": "CPU1 Core Temps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "core0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "coretemp-isa-0000" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "core_0" }
     ]
    },
    {
     "alias": "core1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "coretemp-isa-0000" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "core_1" }
     ]
    },
    {
     "alias": "core2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "coretemp-isa-0000" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "core_2" }
     ]
    },
    {
     "alias": "core3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "coretemp-isa-0000" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "core_8" }
     ]
    },
    {
     "alias": "core4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "coretemp-isa-0000" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "core_9" }
     ]
    },
    {
     "alias": "core5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "coretemp-isa-0000" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "core_10" }
     ]
    }
   ]
  },
  {
   "title": "SDA Disk IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "sda_read_bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" }
     ]
    },
    {
     "alias": "sda_write_bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" }
     ]
    }
   ]
  },
  {
   "title": "Net-Eno1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "bytes_recv",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 5m) FROM \"net\" WHERE (\"interface\" = 'eno1') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eno1" }
     ]
    },
    {
     "alias": "bytes_sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eno1" }
     ]
    }
   ]
  },
  {
   "title": "CPU1 Core Temps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "core0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "coretemp-isa-0001" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "core_0" }
     ]
    },
    {
     "alias": "core1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "coretemp-isa-0001" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "core_1" }
     ]
    },
    {
     "alias": "core2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "coretemp-isa-0001" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "core_2" }
     ]
    },
    {
     "alias": "core3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "coretemp-isa-0001" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "core_8" }
     ]
    },
    {
     "alias": "core4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "coretemp-isa-0001" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "core_9" }
     ]
    },
    {
     "alias": "core5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "coretemp-isa-0001" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "core_10" }
     ]
    }
   ]
  },
  {
   "title": "SDA Disk Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "mapper/r710--vg-root" }
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "mapper/r710--vg-root" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "mapper/r710--vg-root" }
     ]
    }
   ]
  },
  {
   "title": "Net-Eno2",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "bytes_recv",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 5m) FROM \"net\" WHERE (\"interface\" = 'eno1') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eno2" }
     ]
    },
    {
     "alias": "bytes_sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eno2" }
     ]
    }
   ]
  },
  {
   "title": "Watts",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "watts",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "system_level" }
     ]
    }
   ]
  },
  {
   "title": "Ambient Temp",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 15 },
   "targets": [
    {
     "alias": "ambient-temp",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ambient_temp" }
     ]
    }
   ]
  },
  {
   "title": "CPU1 Temp",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "chip" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "SELECT \"temp_input\" FROM \"sensors\" WHERE (\"chip\" = 'coretemp-isa-0000') AND $timeFilter GROUP BY \"chip\"",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "chip", "operator": "=", "value": "coretemp-isa-0000" }
     ]
    }
   ]
  },
  {
   "title": "CPU2 Temp",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "chip" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "SELECT \"temp_input\" FROM \"sensors\" WHERE (\"host\" = 'telegraf' AND \"chip\" = 'coretemp-isa-0001') AND $timeFilter GROUP BY \"chip\"",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "telegraf" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "coretemp-isa-0001" }
     ]
    }
   ]
  },
  {
   "title": "Watts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "watts",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE (\"name\" = 'system_level') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "system_level" }
     ]
    }
   ]
  },
  {
   "title": "Ambient Temp",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "ambient_temp",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE (\"name\" = 'system_level') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ambient_temp" }
     ]
    }
   ]
  },
  {
   "title": "Fan RPM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "fan1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "fan_1_rpm" }
     ]
    },
    {
     "alias": "fan2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "fan_2_rpm" }
     ]
    },
    {
     "alias": "fan3",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "fan_3_rpm" }
     ]
    },
    {
     "alias": "fan4",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "fan_4_rpm" }
     ]
    },
    {
     "alias": "fan5",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "fan_5_rpm" }
     ]
    }
   ]
  }
 ]
}